module.exports = {
	aalt: {
		name: "Austin Alt",
		title: "Admin/Accounts Receivable Clerk",
		email: "austin@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	aallen: {
		name: "Amanda Allen",
		title: "Co-Laboratory Manager",
		email: "amanda.allen@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	aebner: {
		name: "Austin Ebner",
		title: "Co-Laboratory Manager",
		email: "austin.ebner@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	aibsen: {
		name: "Ashlee Ibsen",
		title: "Compliance Officer",
		email: "ashlee.ibsen@compliancemonitoringsystems.com",
		phonenumber: "(406)319-2322",
	},
	ajohanneck: {
		name: "Amber Johanneck",
		title: "24/7 Technician",
		email: "amber.johanneck@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	anealey: {
		name: "Amber Nealey",
		title: "Office Manager",
		email: "amber@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	aprochet: {
		name: "Ashley Prochet",
		title: "Compliance Officer",
		email: "ashley.prochet@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
    athomas: {
        name: "Anna Thomas",
        title: "Compliance Officer",
        email: "Anna.Thomas@compliancemonitoringsystems.com",
        phonenumber: "(406) 393-2455",
    },
    
    bhenderson: {
        name: "Brooklynn Henderson",
        title: "Compliance Officer",
        email: "Brooklynn.henderson@compliancemonitoringsystems.com",
        phonenumber: "(406) 529-1789",
    },
	bhumphreys: {
		name: "Bobbiesue Humphreys",
		title: "Compliance Officer",
		email: "bobbiesue.humphreys@compliancemonitoringsystems.com",
		phonenumber: "(406) 393-2455",
	},
	blathrop: {
		name: "Brandy Lathrop",
		title: "Compliance Officer",
		email: "Brandy.Lathrop@compliancemonitoringsystems.com",
		phonenumber: "(406) 241-9864",
	},
	blavanway: {
		name: "Barry LaVanway",
		title: "Compliance Officer",
		email: "barry@compliancemonitoringsystems.com",
		phonenumber: "(406) 393-2455",
	},
	broberts: {
		name: "Broc Roberts",
		title: "Information Technology (IT)",
		email: "broc@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	    cvislay: {
	        name: "Jessica Adams",
	        title: "Compliance Officer",
	        email: "jessica.adams@compliancemonitoringsystems.com",
	        phonenumber: "(406) 529-1789",
	    },
	dburditt: {
		name: "Darryl Burditt",
		title: "Compliance Officer",
		email: "darryk@compliancemonitoringsystems.com",
		phonenumber: "(406) 450-0164",
	},
	dgeertsen: {
		name: "Devon Geertsen",
		title: "IT Specialist",
		email: "devon.geertsen@compliancemonitoringsystems.com",
		phonenumber: "(406) 531-5242",
	},
	dshepard: {
		name: "Devinne Shepard",
		title: "Compliance Officer",
		email: "devinne@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	gjacobson: {
		name: "Greg Jacobson",
		title: "Community Supervision Officer",
		email: "greg@compliancemonitoringsystems.com",
		phonenumber: "(406) 493-5030",
	},
	chopkins: {
		name: "Cynthia Hopkins",
		title: "Compliance Officer",
		email: "cynthia.hopkins@compliancemonitoringsystems.com",
		phonenumber: "(406) 214-9927",
	},
	cwright: {
		name: "Christopher Wright",
		title: "Compliance Officer",
		email: "christopher.wright@compliancemonitoringsystems.com",
		phonenumber: "(406) 393-2455",
	},
	hroos: {
		name: "Heather Roos",
		title: "Community Corrections Officer",
		email: "heather@communitysupervision.org",
		phonenumber: "(406) 214-7219",
	},
	jharding: {
		name: "Jay Harding",
		title: "Compliance Officer",
		email: "jay.harding@compliancemonitoringsystems.com",
		phonenumber: "(406) 315-3241",
	},
	jhenry: {
		name: "Jake Henry",
		title: "Program Manager",
		email: "jake@compliancemonitoringsystems.com",
		phonenumber: "(406) 531-5242",
	},
	jhyett: {
		name: "Jennifer Hyett",
		title: "Compliance Officer",
		email: "jennifer.hyett@compliancemonitoringsystems.com",
		phonenumber: "(406) 544-5549",
	},
	jmathias: {
		name: "John Mathias",
		title: "Compliance Officer",
		email: "john@compliancemonitoringsystems.com",
		phonenumber: "(406) 544-5549",
	},
	jclairmont: {
		name: "Joleen Clairmont",
		title: "Compliance Officer",
		email: "joleen@compliancemonitoringsystems.com",
		phonenumber: "(406) 493-5030",
	},
	jsickels: {
		name: "Joe Sickels",
		title: "Toxicology Manager",
		email: "joe@compliancemonitoringsystems.com",
		phonenumber: "(406) 370-5262",
	},
	jshelman: {
		name: "John Shelman",
		title: "Compliance Officer",
		email: "john.shelman@compliancemonitoringsystems.com",
		phonenumber: "(406) 241-9864",
	},
	jwallace: {
		name: "John Wallace",
		title: "Compliance Officer",
		email: "john.wallace@compliancemonitoringsystems.com",
		phonenumber: "(406) 274-0155",
	},
    jtardy: {
    name: "Justin Tardy",
    title: "Compliance Officer",
    email: "Justin.Tardy@compliancemonitoringsystems.com",
    phonenumber: "(406) 370-4806",
    },
	jtschida: {
		name: "Jeremy Tschida",
		title: "Team Lead",
		email: "jeremy.tschida@compliancemonitoringsystems.com",
		phonenumber: "(406) 274-0155",
	},
	jtarbert: {
		name: "Jodine Tarbert",
		title: "Chief Executive Officer / Owner",
		email: "jodine@compliancemonitoringsystems.com",
		phonenumber: "(406) 880-2322",
	},
	kkeeler: {
		name: "Katie Keeler",
		title: "Compliance Officer",
		email: "katie@compliancemonitoringsystems.com",
		phonenumber: "(406) 945-9012",
	},
	lhenderson: {
		name: "Lisa Henderson",
		title: "Compliance Officer",
		email: "lisa@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
    llumley: {
        name: "Larry Lumley",
        title: "Compliance Officer",
        email: "larry.lumley@compliancemonitoringsystems.com",
        phonenumber: "(406) 529-1213",
},
	lsingley: {
		name: "Laura B. Singley",
		title: "Compliance Officer",
		email: "laura.singley@compliancemonitoringsystems.com",
		phonenumber: "(406) 493-4061",
	},
    Napierala: {
		name: "Madison Napierala",
		title: "Compliance Officer",
		email: "madison.napierala@compliancemonitoringsystems.com",
		phonenumber: "(406) 274-3089",
	},
	mhills: {
		name: "Marlaina Hills",
		title: "Compliance Officer",
		email: "marlaina.hills@compliancemonitoringsystems.com",
		phonenumber: "(406) 253-0806",
	},
    mhenry: {
        name: "Misti Henry",
        title: "Compliance Officer",
        email: "misty.hendry@compliancemonitoringsystems.com",
        phonenumber: "(406) 370-5958",
    },
	mtamol: {
		name: "Mindi Tamol",
		title: "Administrative Specialist",
		email: "mindi.tamol@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	mtibbetts: {
		name: "Michael Tibbetts",
		title: "Team Lead",
		email: "michael.tibbetts@compliancemonitoringsystems.com",
		phonenumber: "(406) 360-7895",
	},
    mwall: {
        name: "Miranda Wall",
        title: "Administrative Assistant",
        email: "Miranda.Wall@complianceMonitoringsystems.com",
        phonenumber: "(406) 529-1789",
},
	olapka: {
		name: "Olivia Lapka",
		title: "IT Support Specialist",
		email: "olivia.lapka@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	rmclaughlin: {
		name: "Ryley McLaughlin",
		title: "Laboratory Technician / Compliance Officer",
		email: "ryley@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1789",
	},
	rkula: {
		name: "Raquel Kula",
		title: "Community Corrections Officer",
		email: "raquel@compliancemonitoringsystems.com",
		phonenumber: "(406) 529-1213",
	},
	rmurphy: {
		name: "Ross Murphy",
		title: "Team Lead",
		email: "ross.murphy@compliancemonitoringsystems.com",
		phonenumber: "(406) 531-9893",
	},
	tbenjamin: {
		name: "Tiffany Benjamin",
		title: "Monitoring Center Supervisor",
		email: "tiffany@compliancemonitoringsystems.com",
		phonenumber: "(406) 493-4540",
	},
    sallen: {
        name: "Shanley Allen",
        title: "Administrative Assistant",
        mail: "Shanley.Allen@compliancemonitoringsystems.com",
        phonenumber: "(406) 529-1789",
    },
	tfranke: {
		name: "Trina Franke",
		title: "Client Account Services",
		email: "trina.franke@compliancemonitoringsystems.com ",
		phonenumber: "(406) 370-4806",
	},
    tlavanway: {
        name: "Travis LaVanWa",
        title: "Compliance Officer",
        email: "Travis.LaVanway@compliancemonitoringsystems.com",
        phonenumber: "(406) 360-7895",
},
	tstrub: {
		name: "Tate Strub",
		title: "Compliance Officer",
		email: "tate@compliancemonitoringsystems.com",
		phonenumber: "(406) 853-4449",
	},
	tsigglin: {
		name: "Tysen Sigglin",
		title: "Compliance Officer",
		email: "tysen.sigglin@compliancemonitoringsystems.com",
		phonenumber: "(406) 315-3241",
	},
	wwolfe: {
		name: "William Wolfe",
		title: "Compliance Officer",
		email: "william@compliancemonitoringsystems.com",
		phonenumber: "(406) 531-9893",
	},
};
