module.exports = {
  aalt: {
    name: "Austin Alt",
    title: "Admin/Accounts Receivable Clerk",
    email: "austin@compliancemonitoringsystems.com",
    phonenumber: "(406) 529-1789",
  },
  ajohanneck: {
    name: "Amber Johanneck",
    title: "24/7 Technician",
    email: "amber.johanneck@compliancemonitoringsystems.com",
    phonenumber: "(406) 529-1789",
  },
  anealey: {
    name: "Amber Nealey",
    title: "Admin/Accounts Receivable",
    email: "amber@compliancemonitoringsystems.com",
    phonenumber: "(406) 529-1789",
  },
  blavanway: {
    name: "Barry LaVanway",
    title: "Compliance Officer",
    email: "barry@compliancemonitoringsystems.com",
    phonenumber: "(406) 393-2455",
  },
  broberts: {
    name: "Broc Roberts",
    title: "Information Technology (IT)",
    email: "broc@compliancemonitoringsystems.com",
    phonenumber: "(406) 529-1789",
  },
  dshepard: {
    name: "Devinne Shepard",
    title: "Compliance Officer",
    email: "devinne@compliancemonitoringsystems.com",
    phonenumber: "(406) 529-1789",
  },
  gjacobson: {
    name: "Greg Jacobson",
    title: "Community Supervision Officer",
    email: "greg@compliancemonitoringsystems.com",
    phonenumber: "(406) 493-5030",
  },
  chopkins: {
    name: "Cynthia Hopkins",
    title: "Compliance Officer",
    email: "cynthia.hopkins@compliancemonitoringsystems.com",
    phonenumber: "(406) 214-9927",
  },
  hroos: {
    name: "Heather Roos",
    title: "Community Corrections Officer",
    email: "heather@communitysupervision.org",
    phonenumber: "(406) 214-7219",
  },
  jharding: {
    name: "Jay Harding",
    title: "Compliance Officer",
    email: "jay.harding@compliancemonitoringsystems.com",
    phonenumber: "(406) 315-3241",
  },
  jhenry: {
    name: "Jake Henry",
    title: "Program Manager",
    email: "jake@compliancemonitoringsystems.com",
    phonenumber: "(406) 531-5242",
  },
  jhyett: {
    name: "Jennifer Hyett",
    title: "Compliance Officer",
    email: "jennifer.hyett@compliancemonitoringsystems.com",
    phonenumber: "(406) 544-5549",
  },
  jmathias: {
    name: "John Mathias",
    title: "Compliance Officer",
    email: "john@compliancemonitoringsystems.com",
    phonenumber: "(406) 544-5549",
  },
  jclairmont: {
    name: "Joleen Clairmont",
    title: "Compliance Officer",
    email: "joleen@compliancemonitoringsystems.com",
    phonenumber: "(406) 493-5030",
  },
  jsickels: {
    name: "Joe Sickels",
    title: "Lab Manager",
    email: "joe@compliancemonitoringsystems.com",
    phonenumber: "(406) 370-5262",
  },
  jtarbert: {
    name: "Jodine Tarbert",
    title: "Chief Executive Officer / Owner",
    email: "jodine@compliancemonitoringsystems.com",
    phonenumber: "(406) 880-2322",
  },
  kkeeler: {
    name: "Katie Keeler",
    title: "Compliance Officer",
    email: "katie@compliancemonitoringsystems.com",
    phonenumber: "(406) 945-9012",
  },
  mrose: {
    name: "Marisa Rose",
    title: "Compliance Officer",
    email: "marisa@compliancemonitoringsystems.com",
    phonenumber: "(406) 274-3089",
  },
  mhills: {
    name: "Marlaina Hills",
    title: "Compliance Officer",
    email: "marlaina.hills@compliancemonitoringsystems.com",
    phonenumber: "(406) 253-0806",
  },
  mkimmel: {
    name: "Molly Kimmel",
    title: "Compliance Officer",
    email: "molly@compliancemonitoringsystems.com",
    phonenumber: "(406) 370-5958",
  },
  mtamol: {
    name: "Mindi Tamol",
    title: "Compliance Officer",
    email: "molly@compliancemonitoringsystems.com",
    phonenumber: "(406) 370-5958",
  },
  rmclaughlin: {
    name: "Ryley McLaughlin",
    title: "Laboratory Technician / Compliance Officer",
    email: "ryley@compliancemonitoringsystems.com",
    phonenumber: "(406) 529-1789",
  },
  rkula: {
    name: "Raquel Kula",
    title: "Community Corrections Officer",
    email: "raquel@compliancemonitoringsystems.com",
    phonenumber: "(406) 529-1213",
  },
  tbenjiman: {
    name: "Tiffany Benjamin",
    title: "Monitoring Center Supervisor",
    email: "tiffany@compliancemonitoringsystems.com",
    phonenumber: "(406) 493-4540",
  },
  tstrub: {
    name: "Tate Strub",
    title: "Compliance Officer",
    email: "tate@compliancemonitoringsystems.com",
    phonenumber: "(406) 370-4806",
  },
  wwolfe: {
    name: "William Wolfe",
    title: "Compliance Officer",
    email: "william@compliancemonitoringsystems.com",
    phonenumber: "(406) 531-9893",
  },
};
