module.exports = {
  ["adobe"]: { img: require("./img/adobe.png"), type: "img" },
  ["chrome"]: { img: require("./img/chrome.png"), type: "img" },
  ["open_vpn"]: { img: require("./img/open_vpn.png"), type: "img" },
  ["programs"]: { img: require("./img/programs.png"), type: "img" },
  ["drug_patch"]: { img: require("./img/drug_patch.png"), type: "img" },
  ["gps"]: { img: require("./img/gps.png"), type: "img" },
  ["gui"]: { img: "folder-open", type: "icon" },
  ["scram"]: { img: require("./img/scram.png"), type: "img" },
  ["urinalysis"]: { img: require("./img/urinalysis.png"), type: "img" },
  ["txt"]: { img: "file-pdf", type: "icon" },
  ["pdf"]: { img: require("./img/pdf.png"), type: "img" },
  ["mp4"]: { img: require("./img/video.png"), type: "img" },
  ["help"]: { img: require("./img/teacher.png"), type: "img" },
  ["remote_breath"]: { img: require("./img/remote_breath.png"), type: "img" },
  ["documents"]: { img: require("./img/folder.png"), type: "img" },
  ["hair_testing"]: { img: require("./img/hair.jpg"), type: "img" },
  ["docx"]: { img: require("./img/word.png"), type: "img" },
  ["software"]: { img: require("./img/software.png"), type: "img" },
  ["basic"]: { img: require("./img/basic.png"), type: "img" },
  ["advanced"]: { img: require("./img/advanced.png"), type: "img" },
  ["it"]: { img: require("./img/advanced.png"), type: "img" },
  ["download"]: { img: require("./img/download.png"), type: "img" },
  ["downloads"]: { img: require("./img/download.png"), type: "img" },
  ["exe"]: { img: require("./img/cogs.png"), type: "img" },
  ["zip"]: { img: require("./img/zip.png"), type: "img" },
  ["xlsx"]: { img: require("./img/excel.png"), type: "img" },
  ["xls"]: { img: require("./img/excel.png"), type: "img" },
  ["csv"]: { img: require("./img/excel.png"), type: "img" },
  ["office_365"]: { img: require("./img/office365.png"), type: "img" },
  ["o365"]: { img: require("./img/office365.png"), type: "img" },
  ["office_2010"]: { img: require("./img/office_2010.png"), type: "img" },
  ["o2010"]: { img: require("./img/office_2010.png"), type: "img" },
  ["direct_connect"]: { img: require("./img/direct_connect.png"), type: "img" },
  ["printer"]: { img: require("./img/printer.png"), type: "img" },
  ["printers"]: { img: require("./img/printer.png"), type: "img" },
  ["microsoft_teams"]: { img: require("./img/ms_teams.png"), type: "img" },
  ["ms_teams"]: { img: require("./img/ms_teams.png"), type: "img" },
  ["webroot"]: { img: require("./img/webroot.png"), type: "img" },
  ["cms"]: { img: require("./img/cms.png"), type: "img" },
  ["compliancemonitoringsystems"]: {
    img: require("./img/cms.png"),
    type: "img"
  },
  ["compliancemonitoringsystems.com"]: {
    img: require("./img/cms.png"),
    type: "img"
  },
  ["compliance_monitoring_systems"]: {
    img: require("./img/cms.png"),
    type: "img"
  },
  ["link"]: { img: require("./img/link.png"), type: "img" },
  ["LINK"]: { img: require("./img/link.png"), type: "img" },
  ["missoula"]: { img: require("./img/missoula.png"), type: "img" },
  ["hamilton"]: { img: require("./img/hamilton.png"), type: "img" },
  ["kalispell"]: { img: require("./img/kalispell.png"), type: "img" },
  ["bozeman"]: { img: require("./img/bozeman.png"), type: "img" },
  ["great_falls"]: { img: require("./img/great_falls.png"), type: "img" },
  ["_default"]: { img: "file-pdf", type: "icon" }
};
